name: oracle

services:
  oracle:
    image: gvenzl/oracle-free:latest # Oracle Database Free の公式イメージ
    container_name: oracle
    ports:
      - "1521:1521" # Oracle 接続用
    environment:
      ORACLE_PASSWORD: oracle # 管理者パスワード
      APP_USER: task
      APP_USER_PASSWORD: password
